[".local/custom/templates/Eisvogel"]
    type = "git-repo"
    url = "https://github.com/Wandmalfarbe/pandoc-latex-template.git"
    refreshPeriod = "168h"
    [".local/custom/templates/Eisvogel".pull]
        args = ["--ff-only"]
[".config/ranger/plugins/devicons2"]
    type = "git-repo"
    url = "https://github.com/cdump/ranger-devicons2"
    refreshPeriod = "168h"
    [".config/ranger/plugins/devicons2".pull]
        args = ["--ff-only"]

