[theme]
theme = "semi-native"

[icons]
icons = "awesome5"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "net"
device = "enp0s31f6"
format = "$ip $speed_down $graph_down"
interval = 5

[[block]]
block = "net"
device = "tailscale0"
format = "$ip $speed_down $graph_down"
interval = 5

[[block]]
block = "load"
interval = 1
format = " $icon 1 min avg: $1m.eng(w:4) "


# [[block]]
# block = "battery"
# interval = 10
# driver = "upower"
# format = "{percentage}% {time}"

[[block]]
block = "time"
format = "IST $icon: $timestamp.datetime(f:'%a %d/%m %R')"
timezone = "Asia/Kolkata"
interval = 60

[[block]]
block = "time"
interval = 60
format = "ET $icon: $timestamp.datetime(f:'%a %d/%m %R')"
